pass format parameter to captureScreenshot
sibson/vncdotool pull request #249
Opened 2023-02-06 01:18 UTC by reiinakano

It's useful to pass in the Pillow `format` parameter if I want to save the captured screenshot in a `BytesIO` object.

2023-02-06 06:19 UTC, pmhahn requested changes
- [ ] In general okay, but please add PEP-484 type hints.
- [ ] `format` is not passed through in one case
- [ ] for consistency please also change `captureRegion()` to get the new `format` parameter.
- [ ] The parameter name `filename` suggests, that only _filenames_ should be used, but [Image.save](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) supports `pathlib.Path` and _opened binary files_, too. As such it might make sense to rename the parameter to reflect this:

```diff
diff --git vncdotool/client.py vncdotool/client.py
index 83b9512..65bd188 100644
--- vncdotool/client.py
+++ vncdotool/client.py
@@ -10,8 +10,9 @@ import logging
 import math
 import socket
 import time
+from pathlib import Path
 from struct import pack
-from typing import Any, List, Optional, TypeVar
+from typing import IO, Any, List, Optional, TypeVar, Union
 
 from twisted.internet import reactor
 from twisted.internet.defer import Deferred
@@ -22,6 +23,7 @@ from twisted.python.failure import Failure
 from . import rfb
 
 TClient = TypeVar("TClient", bound="VNCDoToolClient")
+TFile = Union[str, Path, IO[bytes]]
 
 log = logging.getLogger(__name__)
 
@@ -251,36 +253,36 @@ class VNCDoToolClient(rfb.RFBClient):
 
         return self
 
-    def captureScreen(self, filename: str, incremental: bool = False) -> Deferred:
+    def captureScreen(self, fp: TFile, incremental: bool = False) -> Deferred:
         """ Save the current display to filename
         """
-        log.debug('captureScreen %s', filename)
-        return self._capture(filename, incremental)
+        log.debug('captureScreen %s', fp)
+        return self._capture(fp, incremental)
 
-    def captureRegion(self, filename: str, x: int, y: int, w: int, h: int, incremental: bool = False) -> Deferred:
+    def captureRegion(self, fp: TFile, x: int, y: int, w: int, h: int, incremental: bool = False) -> Deferred:
         """ Save a region of the current display to filename
         """
-        log.debug('captureRegion %s', filename)
-        return self._capture(filename, incremental, x, y, x + w, y + h)
+        log.debug('captureRegion %s', fp)
+        return self._capture(fp, incremental, x, y, x + w, y + h)
 
     def refreshScreen(self, incremental: bool = False) -> Deferred:
         d = self.deferred = Deferred()
         self.framebufferUpdateRequest(incremental=incremental)
         return d
 
-    def _capture(self, filename: str, incremental: bool, *args: int) -> Deferred:
+    def _capture(self, fp: TFile, incremental: bool, *args: int) -> Deferred:
         d = self.refreshScreen(incremental)
-        d.addCallback(self._captureSave, filename, *args)
+        d.addCallback(self._captureSave, fp, *args)
         return d
 
-    def _captureSave(self: TClient, data: object, filename: str, *args: int) -> TClient:
-        log.debug('captureSave %s', filename)
+    def _captureSave(self: TClient, data: object, fp: TFile, *args: int) -> TClient:
+        log.debug('captureSave %s', fp)
         assert self.screen is not None
         if args:
             capture = self.screen.crop(args)  # type: ignore[arg-type]
         else:
             capture = self.screen
-        capture.save(filename)
+        capture.save(fp)
 
         return self
 
```

2023-02-06 06:19 UTC, pmhahn commented on vncdotool/client.py
> +    def captureScreen(self, filename: str, incremental: bool = False, format=None) -> Deferred:
Please add PEP-484 type hints:
```suggestion
    def captureScreen(self, filename: str, incremental: bool = False, format: Optional[str] = None) -> Deferred:
```

2023-02-06 06:19 UTC, pmhahn commented on vncdotool/client.py
> +        return self._capture(filename, incremental, format=None)
This looks wrong: You probably want to pass through the format here:
```suggestion
        return self._capture(filename, incremental, format=format)
```

2023-02-06 06:19 UTC, pmhahn commented on vncdotool/client.py
> +    def _capture(self, filename: str, incremental: bool, *args: int, **kwargs) -> Deferred:
Type hints please:
```suggestion
    def _capture(self, filename: str, incremental: bool, *args: int, **kwargs: Any) -> Deferred:
```

2023-02-06 06:19 UTC, pmhahn commented on vncdotool/client.py
> +    def _captureSave(self: TClient, data: object, filename: str, *args: int, **kwargs) -> TClient:
Type hints please:
```suggestion
    def _captureSave(self: TClient, data: object, filename: str, *args: int, **kwargs: Any) -> TClient:
```

2024-11-12 18:45 UTC, closed without merging

2025-01-19 17:47 UTC, Neustradamus commented
@reiinakano: Why have you closed your PR?